// Generated by Scripts/generate-agency-identifiers.py. Edit the generator, not this file.
// Source: https://www.federalregister.gov/api/v1/agencies.json
// Snapshot SHA-256: 7a806d209d75ee543e6e91506e485ec6a8f42687056e14a1484c8bc9e79f5443

extension AgencyIdentifier {
  /// ACTION (`action`).
  public static let action = Self(rawValue: "action")
  /// Administration Office, Executive Office of the President (`administration-office-executive-office-of-the-president`).
  public static let administrationOfficeExecutiveOfficeOfThePresident = Self(
    rawValue: "administration-office-executive-office-of-the-president")
  /// Administrative Conference of the United States (`administrative-conference-of-the-united-states`).
  public static let administrativeConferenceOfTheUnitedStates = Self(
    rawValue: "administrative-conference-of-the-united-states")
  /// Administrative Office of United States Courts (`administrative-office-of-united-states-courts`).
  public static let administrativeOfficeOfUnitedStatesCourts = Self(
    rawValue: "administrative-office-of-united-states-courts")
  /// Advisory Council on Historic Preservation (`advisory-council-on-historic-preservation`).
  public static let advisoryCouncilOnHistoricPreservation = Self(
    rawValue: "advisory-council-on-historic-preservation")
  /// Advocacy and Outreach Office (`advocacy-and-outreach-office`).
  public static let advocacyAndOutreachOffice = Self(rawValue: "advocacy-and-outreach-office")
  /// United States African Development Foundation (`african-development-foundation`).
  public static let africanDevelopmentFoundation = Self(rawValue: "african-development-foundation")
  /// Agency for Healthcare Research and Quality (`agency-for-healthcare-research-and-quality`).
  public static let agencyForHealthcareResearchAndQuality = Self(
    rawValue: "agency-for-healthcare-research-and-quality")
  /// Agency for International Development (`agency-for-international-development`).
  public static let agencyForInternationalDevelopment = Self(
    rawValue: "agency-for-international-development")
  /// Agency for Toxic Substances and Disease Registry (`agency-for-toxic-substances-and-disease-registry`).
  public static let agencyForToxicSubstancesAndDiseaseRegistry = Self(
    rawValue: "agency-for-toxic-substances-and-disease-registry")
  /// Aging Administration (`aging-administration`).
  public static let agingAdministration = Self(rawValue: "aging-administration")
  /// Agricultural Marketing Service (`agricultural-marketing-service`).
  public static let agriculturalMarketingService = Self(rawValue: "agricultural-marketing-service")
  /// Agricultural Research Service (`agricultural-research-service`).
  public static let agriculturalResearchService = Self(rawValue: "agricultural-research-service")
  /// Agriculture Department (`agriculture-department`).
  public static let agricultureDepartment = Self(rawValue: "agriculture-department")
  /// Air Force Department (`air-force-department`).
  public static let airForceDepartment = Self(rawValue: "air-force-department")
  /// Air Quality National Commission (`air-quality-national-commission`).
  public static let airQualityNationalCommission = Self(rawValue: "air-quality-national-commission")
  /// Air Transportation Stabilization Board (`air-transportation-stabilization-board`).
  public static let airTransportationStabilizationBoard = Self(
    rawValue: "air-transportation-stabilization-board")
  /// Alaska Power Administration (`alaska-power-administration`).
  public static let alaskaPowerAdministration = Self(rawValue: "alaska-power-administration")
  /// Alcohol and Tobacco Tax and Trade Bureau (`alcohol-and-tobacco-tax-and-trade-bureau`).
  public static let alcoholAndTobaccoTaxAndTradeBureau = Self(
    rawValue: "alcohol-and-tobacco-tax-and-trade-bureau")
  /// Alcohol, Tobacco, Firearms, and Explosives Bureau (`alcohol-tobacco-firearms-and-explosives-bureau`).
  public static let alcoholTobaccoFirearmsAndExplosivesBureau = Self(
    rawValue: "alcohol-tobacco-firearms-and-explosives-bureau")
  /// American Battle Monuments Commission (`american-battle-monuments-commission`).
  public static let americanBattleMonumentsCommission = Self(
    rawValue: "american-battle-monuments-commission")
  /// Amtrak Reform Council (`amtrak-reform-council`).
  public static let amtrakReformCouncil = Self(rawValue: "amtrak-reform-council")
  /// Animal and Plant Health Inspection Service (`animal-and-plant-health-inspection-service`).
  public static let animalAndPlantHealthInspectionService = Self(
    rawValue: "animal-and-plant-health-inspection-service")
  /// Antitrust Division (`antitrust-division`).
  public static let antitrustDivision = Self(rawValue: "antitrust-division")
  /// Antitrust Modernization Commission (`antitrust-modernization-commission`).
  public static let antitrustModernizationCommission = Self(
    rawValue: "antitrust-modernization-commission")
  /// Appalachian Regional Commission (`appalachian-regional-commission`).
  public static let appalachianRegionalCommission = Self(
    rawValue: "appalachian-regional-commission")
  /// Appalachian States Low-Level Radioactive Waste Commission (`appalachian-states-low-level-radioactive-waste-commission`).
  public static let appalachianStatesLowLevelRadioactiveWasteCommission = Self(
    rawValue: "appalachian-states-low-level-radioactive-waste-commission")
  /// Appraisal Subcommittee of the Federal Financial Institutions Examination Council (`appraisal-subcommittee-of-the-federal-financial-institutions-examination-council`).
  public static let appraisalSubcommitteeOfTheFederalFinancialInstitutionsExaminationCouncil = Self(
    rawValue: "appraisal-subcommittee-of-the-federal-financial-institutions-examination-council")
  /// Architect of the Capitol (`architect-of-the-capitol`).
  public static let architectOfTheCapitol = Self(rawValue: "architect-of-the-capitol")
  /// Architectural and Transportation Barriers Compliance Board (`architectural-and-transportation-barriers-compliance-board`).
  public static let architecturalAndTransportationBarriersComplianceBoard = Self(
    rawValue: "architectural-and-transportation-barriers-compliance-board")
  /// Arctic Research Commission (`arctic-research-commission`).
  public static let arcticResearchCommission = Self(rawValue: "arctic-research-commission")
  /// Armed Forces Retirement Home (`armed-forces-retirement-home`).
  public static let armedForcesRetirementHome = Self(rawValue: "armed-forces-retirement-home")
  /// Arms Control and Disarmament Agency (`arms-control-and-disarmament-agency`).
  public static let armsControlAndDisarmamentAgency = Self(
    rawValue: "arms-control-and-disarmament-agency")
  /// Army Department (`army-department`).
  public static let armyDepartment = Self(rawValue: "army-department")
  /// Assassination Records Review Board (`assassination-records-review-board`).
  public static let assassinationRecordsReviewBoard = Self(
    rawValue: "assassination-records-review-board")
  /// Barry M. Goldwater Scholarship and Excellence in Education Foundation (`barry-m-goldwater-scholarship-and-excellence-in-education-foundation`).
  public static let barryMGoldwaterScholarshipAndExcellenceInEducationFoundation = Self(
    rawValue: "barry-m-goldwater-scholarship-and-excellence-in-education-foundation")
  /// Benefits Review Board (`benefits-review-board`).
  public static let benefitsReviewBoard = Self(rawValue: "benefits-review-board")
  /// Bipartisan Commission on Entitlement and Tax Reform (`bipartisan-commission-on-entitlement-and-tax-reform`).
  public static let bipartisanCommissionOnEntitlementAndTaxReform = Self(
    rawValue: "bipartisan-commission-on-entitlement-and-tax-reform")
  /// Board of Directors of the Hope for Homeowners Program (`board-of-directors-of-the-hope-for-homeowners-program`).
  public static let boardOfDirectorsOfTheHopeForHomeownersProgram = Self(
    rawValue: "board-of-directors-of-the-hope-for-homeowners-program")
  /// Bonneville Power Administration (`bonneville-power-administration`).
  public static let bonnevillePowerAdministration = Self(
    rawValue: "bonneville-power-administration")
  /// Broadcasting Board of Governors (`broadcasting-board-of-governors`).
  public static let broadcastingBoardOfGovernors = Self(rawValue: "broadcasting-board-of-governors")
  /// Bureau of the Fiscal Service (`bureau-of-the-fiscal-service`).
  public static let bureauOfTheFiscalService = Self(rawValue: "bureau-of-the-fiscal-service")
  /// Census Bureau (`census-bureau`).
  public static let censusBureau = Self(rawValue: "census-bureau")
  /// Census Monitoring Board (`census-monitoring-board`).
  public static let censusMonitoringBoard = Self(rawValue: "census-monitoring-board")
  /// Centers for Disease Control and Prevention (`centers-for-disease-control-and-prevention`).
  public static let centersForDiseaseControlAndPrevention = Self(
    rawValue: "centers-for-disease-control-and-prevention")
  /// Centers for Medicare & Medicaid Services (`centers-for-medicare-medicaid-services`).
  public static let centersForMedicareMedicaidServices = Self(
    rawValue: "centers-for-medicare-medicaid-services")
  /// Central Intelligence Agency (`central-intelligence-agency`).
  public static let centralIntelligenceAgency = Self(rawValue: "central-intelligence-agency")
  /// Chemical Safety and Hazard Investigation Board (`chemical-safety-and-hazard-investigation-board`).
  public static let chemicalSafetyAndHazardInvestigationBoard = Self(
    rawValue: "chemical-safety-and-hazard-investigation-board")
  /// Child Support Enforcement Office (`child-support-enforcement-office`).
  public static let childSupportEnforcementOffice = Self(
    rawValue: "child-support-enforcement-office")
  /// Children and Families Administration (`children-and-families-administration`).
  public static let childrenAndFamiliesAdministration = Self(
    rawValue: "children-and-families-administration")
  /// Christopher Columbus Quincentenary Jubilee Commission (`christopher-columbus-quincentenary-jubilee-commission`).
  public static let christopherColumbusQuincentenaryJubileeCommission = Self(
    rawValue: "christopher-columbus-quincentenary-jubilee-commission")
  /// Civil Rights Cold Case Records Review Board (`civil-rights-cold-case-records-review-board`).
  public static let civilRightsColdCaseRecordsReviewBoard = Self(
    rawValue: "civil-rights-cold-case-records-review-board")
  /// Civil Rights Commission (`civil-rights-commission`).
  public static let civilRightsCommission = Self(rawValue: "civil-rights-commission")
  /// Coast Guard (`coast-guard`).
  public static let coastGuard = Self(rawValue: "coast-guard")
  /// Commerce Department (`commerce-department`).
  public static let commerceDepartment = Self(rawValue: "commerce-department")
  /// Commercial Space Transportation Office (`commercial-space-transportation-office`).
  public static let commercialSpaceTransportationOffice = Self(
    rawValue: "commercial-space-transportation-office")
  /// Commission of Fine Arts (`commission-of-fine-arts`).
  public static let commissionOfFineArts = Self(rawValue: "commission-of-fine-arts")
  /// Commission on Immigration Reform (`commission-on-immigration-reform`).
  public static let commissionOnImmigrationReform = Self(
    rawValue: "commission-on-immigration-reform")
  /// Commission on Protecting and Reducing Government Secrecy (`commission-on-protecting-and-reducing-government-secrecy`).
  public static let commissionOnProtectingAndReducingGovernmentSecrecy = Self(
    rawValue: "commission-on-protecting-and-reducing-government-secrecy")
  /// Commission on Review of Overseas Military Facility Structure of the United States (`commission-on-review-of-overseas-military-facility-structure-of-the-united-states`).
  public static let commissionOnReviewOfOverseasMilitaryFacilityStructureOfTheUnitedStates = Self(
    rawValue: "commission-on-review-of-overseas-military-facility-structure-of-the-united-states")
  /// Commission on Structural Alternatives for the Federal Courts of Appeals (`commission-on-structural-alternatives-for-the-federal-courts-of-appeals`).
  public static let commissionOnStructuralAlternativesForTheFederalCourtsOfAppeals = Self(
    rawValue: "commission-on-structural-alternatives-for-the-federal-courts-of-appeals")
  /// Commission on the Advancement of Federal Law Enforcement (`commission-on-the-advancement-of-federal-law-enforcement`).
  public static let commissionOnTheAdvancementOfFederalLawEnforcement = Self(
    rawValue: "commission-on-the-advancement-of-federal-law-enforcement")
  /// Commission on the Bicentennial of the United States Constitution (`commission-on-the-bicentennial-of-the-united-states-constitution`).
  public static let commissionOnTheBicentennialOfTheUnitedStatesConstitution = Self(
    rawValue: "commission-on-the-bicentennial-of-the-united-states-constitution")
  /// Commission on the Future of the United States Aerospace Industry (`commission-on-the-future-of-the-united-states-aerospace-industry`).
  public static let commissionOnTheFutureOfTheUnitedStatesAerospaceIndustry = Self(
    rawValue: "commission-on-the-future-of-the-united-states-aerospace-industry")
  /// Commission on the Social Security Notch Issue (`commission-on-the-social-security-notch-issue`).
  public static let commissionOnTheSocialSecurityNotchIssue = Self(
    rawValue: "commission-on-the-social-security-notch-issue")
  /// Committee for Purchase From People Who Are Blind or Severely Disabled (`committee-for-purchase-from-people-who-are-blind-or-severely-disabled`).
  public static let committeeForPurchaseFromPeopleWhoAreBlindOrSeverelyDisabled = Self(
    rawValue: "committee-for-purchase-from-people-who-are-blind-or-severely-disabled")
  /// Committee for the Implementation of Textile Agreements (`committee-for-the-implementation-of-textile-agreements`).
  public static let committeeForTheImplementationOfTextileAgreements = Self(
    rawValue: "committee-for-the-implementation-of-textile-agreements")
  /// Commodity Credit Corporation (`commodity-credit-corporation`).
  public static let commodityCreditCorporation = Self(rawValue: "commodity-credit-corporation")
  /// Commodity Futures Trading Commission (`commodity-futures-trading-commission`).
  public static let commodityFuturesTradingCommission = Self(
    rawValue: "commodity-futures-trading-commission")
  /// Community Development Financial Institutions Fund (`community-development-financial-institutions-fund`).
  public static let communityDevelopmentFinancialInstitutionsFund = Self(
    rawValue: "community-development-financial-institutions-fund")
  /// Community Living Administration (`community-living-administration`).
  public static let communityLivingAdministration = Self(
    rawValue: "community-living-administration")
  /// Competitiveness Policy Council (`competitiveness-policy-council`).
  public static let competitivenessPolicyCouncil = Self(rawValue: "competitiveness-policy-council")
  /// Comptroller of the Currency (`comptroller-of-the-currency`).
  public static let comptrollerOfTheCurrency = Self(rawValue: "comptroller-of-the-currency")
  /// Congressional Budget Office (`congressional-budget-office`).
  public static let congressionalBudgetOffice = Self(rawValue: "congressional-budget-office")
  /// Consumer Financial Protection Bureau (`consumer-financial-protection-bureau`).
  public static let consumerFinancialProtectionBureau = Self(
    rawValue: "consumer-financial-protection-bureau")
  /// Consumer Product Safety Commission (`consumer-product-safety-commission`).
  public static let consumerProductSafetyCommission = Self(
    rawValue: "consumer-product-safety-commission")
  /// Cooperative State Research, Education, and Extension Service (`cooperative-state-research-education-and-extension-service`).
  public static let cooperativeStateResearchEducationAndExtensionService = Self(
    rawValue: "cooperative-state-research-education-and-extension-service")
  /// Coordinating Council on Juvenile Justice and Delinquency Prevention (`coordinating-council-on-juvenile-justice-and-delinquency-prevention`).
  public static let coordinatingCouncilOnJuvenileJusticeAndDelinquencyPrevention = Self(
    rawValue: "coordinating-council-on-juvenile-justice-and-delinquency-prevention")
  /// Copyright Office, Library of Congress (`copyright-office-library-of-congress`).
  public static let copyrightOfficeLibraryOfCongress = Self(
    rawValue: "copyright-office-library-of-congress")
  /// Copyright Royalty Board (`copyright-royalty-board`).
  public static let copyrightRoyaltyBoard = Self(rawValue: "copyright-royalty-board")
  /// Copyright Royalty Judges (`copyright-royalty-judges`).
  public static let copyrightRoyaltyJudges = Self(rawValue: "copyright-royalty-judges")
  /// Corporation for National and Community Service (`corporation-for-national-and-community-service`).
  public static let corporationForNationalAndCommunityService = Self(
    rawValue: "corporation-for-national-and-community-service")
  /// Council of the Inspectors General on Integrity and Efficiency (`council-of-the-inspectors-general-on-integrity-and-efficiency`).
  public static let councilOfTheInspectorsGeneralOnIntegrityAndEfficiency = Self(
    rawValue: "council-of-the-inspectors-general-on-integrity-and-efficiency")
  /// Council on Environmental Quality (`council-on-environmental-quality`).
  public static let councilOnEnvironmentalQuality = Self(
    rawValue: "council-on-environmental-quality")
  /// Counsel to the President (`counsel-to-the-president`).
  public static let counselToThePresident = Self(rawValue: "counsel-to-the-president")
  /// Court Services and Offender Supervision Agency for the District of Columbia (`court-services-and-offender-supervision-agency-for-the-district-of-columbia`).
  public static let courtServicesAndOffenderSupervisionAgencyForTheDistrictOfColumbia = Self(
    rawValue: "court-services-and-offender-supervision-agency-for-the-district-of-columbia")
  /// Crime and Security in U.S. Seaports, Interagency Commission (`crime-and-security-in-u-s-seaports-interagency-commission`).
  public static let crimeAndSecurityInUSSeaportsInteragencyCommission = Self(
    rawValue: "crime-and-security-in-u-s-seaports-interagency-commission")
  /// Customs Service (`customs-service`).
  public static let customsService = Self(rawValue: "customs-service")
  /// Defense Acquisition Regulations System (`defense-acquisition-regulations-system`).
  public static let defenseAcquisitionRegulationsSystem = Self(
    rawValue: "defense-acquisition-regulations-system")
  /// Defense Base Closure and Realignment Commission (`defense-base-closure-and-realignment-commission`).
  public static let defenseBaseClosureAndRealignmentCommission = Self(
    rawValue: "defense-base-closure-and-realignment-commission")
  /// Defense Contract Audit Agency (`defense-contract-audit-agency`).
  public static let defenseContractAuditAgency = Self(rawValue: "defense-contract-audit-agency")
  /// Defense Criminal Investigative Service (`defense-criminal-investigative-service`).
  public static let defenseCriminalInvestigativeService = Self(
    rawValue: "defense-criminal-investigative-service")
  /// Defense Department (`defense-department`).
  public static let defenseDepartment = Self(rawValue: "defense-department")
  /// Defense Information Systems Agency (`defense-information-systems-agency`).
  public static let defenseInformationSystemsAgency = Self(
    rawValue: "defense-information-systems-agency")
  /// Defense Intelligence Agency (`defense-intelligence-agency`).
  public static let defenseIntelligenceAgency = Self(rawValue: "defense-intelligence-agency")
  /// Defense Investigative Service (`defense-investigative-service`).
  public static let defenseInvestigativeService = Self(rawValue: "defense-investigative-service")
  /// Defense Logistics Agency (`defense-logistics-agency`).
  public static let defenseLogisticsAgency = Self(rawValue: "defense-logistics-agency")
  /// Defense Mapping Agency (`defense-mapping-agency`).
  public static let defenseMappingAgency = Self(rawValue: "defense-mapping-agency")
  /// Defense Nuclear Facilities Safety Board (`defense-nuclear-facilities-safety-board`).
  public static let defenseNuclearFacilitiesSafetyBoard = Self(
    rawValue: "defense-nuclear-facilities-safety-board")
  /// Defense Special Weapons Agency (`defense-special-weapons-agency`).
  public static let defenseSpecialWeaponsAgency = Self(rawValue: "defense-special-weapons-agency")
  /// Delaware River Basin Commission (`delaware-river-basin-commission`).
  public static let delawareRiverBasinCommission = Self(rawValue: "delaware-river-basin-commission")
  /// Delta Regional Authority (`delta-regional-authority`).
  public static let deltaRegionalAuthority = Self(rawValue: "delta-regional-authority")
  /// Denali Commission (`denali-commission`).
  public static let denaliCommission = Self(rawValue: "denali-commission")
  /// Disability Employment Policy Office (`disability-employment-policy-office`).
  public static let disabilityEmploymentPolicyOffice = Self(
    rawValue: "disability-employment-policy-office")
  /// Drug Enforcement Administration (`drug-enforcement-administration`).
  public static let drugEnforcementAdministration = Self(
    rawValue: "drug-enforcement-administration")
  /// Economic Analysis Bureau (`economic-analysis-bureau`).
  public static let economicAnalysisBureau = Self(rawValue: "economic-analysis-bureau")
  /// Economic Analysis Staff (`economic-analysis-staff`).
  public static let economicAnalysisStaff = Self(rawValue: "economic-analysis-staff")
  /// Economic Development Administration (`economic-development-administration`).
  public static let economicDevelopmentAdministration = Self(
    rawValue: "economic-development-administration")
  /// Economic Research Service (`economic-research-service`).
  public static let economicResearchService = Self(rawValue: "economic-research-service")
  /// Economics and Statistics Administration (`economics-and-statistics-administration`).
  public static let economicsAndStatisticsAdministration = Self(
    rawValue: "economics-and-statistics-administration")
  /// Education Department (`education-department`).
  public static let educationDepartment = Self(rawValue: "education-department")
  /// Election Assistance Commission (`election-assistance-commission`).
  public static let electionAssistanceCommission = Self(rawValue: "election-assistance-commission")
  /// Electronic Commerce Advisory Commission (`electronic-commerce-advisory-commission`).
  public static let electronicCommerceAdvisoryCommission = Self(
    rawValue: "electronic-commerce-advisory-commission")
  /// Emergency Oil and Gas Guaranteed Loan Board (`emergency-oil-and-gas-guaranteed-loan-board`).
  public static let emergencyOilAndGasGuaranteedLoanBoard = Self(
    rawValue: "emergency-oil-and-gas-guaranteed-loan-board")
  /// Emergency Steel Guarantee Loan Board (`emergency-steel-guarantee-loan-board`).
  public static let emergencySteelGuaranteeLoanBoard = Self(
    rawValue: "emergency-steel-guarantee-loan-board")
  /// Employee Benefits Security Administration (`employee-benefits-security-administration`).
  public static let employeeBenefitsSecurityAdministration = Self(
    rawValue: "employee-benefits-security-administration")
  /// Employees Compensation Appeals Board (`employees-compensation-appeals-board`).
  public static let employeesCompensationAppealsBoard = Self(
    rawValue: "employees-compensation-appeals-board")
  /// Employment and Training Administration (`employment-and-training-administration`).
  public static let employmentAndTrainingAdministration = Self(
    rawValue: "employment-and-training-administration")
  /// Employment Standards Administration (`employment-standards-administration`).
  public static let employmentStandardsAdministration = Self(
    rawValue: "employment-standards-administration")
  /// Energy and Environmental Policy Office (`energy-and-environmental-policy-office`).
  public static let energyAndEnvironmentalPolicyOffice = Self(
    rawValue: "energy-and-environmental-policy-office")
  /// Energy Department (`energy-department`).
  public static let energyDepartment = Self(rawValue: "energy-department")
  /// Energy Efficiency and Renewable Energy Office (`energy-efficiency-and-renewable-energy-office`).
  public static let energyEfficiencyAndRenewableEnergyOffice = Self(
    rawValue: "energy-efficiency-and-renewable-energy-office")
  /// Energy Information Administration (`energy-information-administration`).
  public static let energyInformationAdministration = Self(
    rawValue: "energy-information-administration")
  /// Energy Policy and New Uses Office (`energy-policy-and-new-uses-office`).
  public static let energyPolicyAndNewUsesOffice = Self(
    rawValue: "energy-policy-and-new-uses-office")
  /// Energy Research Office (`energy-research-office`).
  public static let energyResearchOffice = Self(rawValue: "energy-research-office")
  /// Engineers Corps (`engineers-corps`).
  public static let engineersCorps = Self(rawValue: "engineers-corps")
  /// Engraving and Printing Bureau (`engraving-and-printing-bureau`).
  public static let engravingAndPrintingBureau = Self(rawValue: "engraving-and-printing-bureau")
  /// Environment Office, Energy Department (`environment-office-energy-department`).
  public static let environmentOfficeEnergyDepartment = Self(
    rawValue: "environment-office-energy-department")
  /// Environmental Protection Agency (`environmental-protection-agency`).
  public static let environmentalProtectionAgency = Self(
    rawValue: "environmental-protection-agency")
  /// Equal Employment Opportunity Commission (`equal-employment-opportunity-commission`).
  public static let equalEmploymentOpportunityCommission = Self(
    rawValue: "equal-employment-opportunity-commission")
  /// Executive Council on Integrity and Efficiency (`executive-council-on-integrity-and-efficiency`).
  public static let executiveCouncilOnIntegrityAndEfficiency = Self(
    rawValue: "executive-council-on-integrity-and-efficiency")
  /// Executive Office for Immigration Review (`executive-office-for-immigration-review`).
  public static let executiveOfficeForImmigrationReview = Self(
    rawValue: "executive-office-for-immigration-review")
  /// Executive Office of the President (`executive-office-of-the-president`).
  public static let executiveOfficeOfThePresident = Self(
    rawValue: "executive-office-of-the-president")
  /// Export Administration Bureau (`export-administration-bureau`).
  public static let exportAdministrationBureau = Self(rawValue: "export-administration-bureau")
  /// Export-Import Bank (`export-import-bank`).
  public static let exportImportBank = Self(rawValue: "export-import-bank")
  /// Family Assistance Office (`family-assistance-office`).
  public static let familyAssistanceOffice = Self(rawValue: "family-assistance-office")
  /// Farm Credit Administration (`farm-credit-administration`).
  public static let farmCreditAdministration = Self(rawValue: "farm-credit-administration")
  /// Farm Credit System Insurance Corporation (`farm-credit-system-insurance-corporation`).
  public static let farmCreditSystemInsuranceCorporation = Self(
    rawValue: "farm-credit-system-insurance-corporation")
  /// Farm Production and Conservation Business Center (`farm-production-and-conservation-business-center`).
  public static let farmProductionAndConservationBusinessCenter = Self(
    rawValue: "farm-production-and-conservation-business-center")
  /// Farm Service Agency (`farm-service-agency`).
  public static let farmServiceAgency = Self(rawValue: "farm-service-agency")
  /// Federal Accounting Standards Advisory Board (`federal-accounting-standards-advisory-board`).
  public static let federalAccountingStandardsAdvisoryBoard = Self(
    rawValue: "federal-accounting-standards-advisory-board")
  /// Federal Acquisition Regulation System (`federal-acquisition-regulation-system`).
  public static let federalAcquisitionRegulationSystem = Self(
    rawValue: "federal-acquisition-regulation-system")
  /// Federal Aviation Administration (`federal-aviation-administration`).
  public static let federalAviationAdministration = Self(
    rawValue: "federal-aviation-administration")
  /// Federal Bureau of Investigation (`federal-bureau-of-investigation`).
  public static let federalBureauOfInvestigation = Self(rawValue: "federal-bureau-of-investigation")
  /// Federal Communications Commission (`federal-communications-commission`).
  public static let federalCommunicationsCommission = Self(
    rawValue: "federal-communications-commission")
  /// Federal Contract Compliance Programs Office (`federal-contract-compliance-programs-office`).
  public static let federalContractComplianceProgramsOffice = Self(
    rawValue: "federal-contract-compliance-programs-office")
  /// Federal Council on the Arts and the Humanities (`federal-council-on-the-arts-and-the-humanities`).
  public static let federalCouncilOnTheArtsAndTheHumanities = Self(
    rawValue: "federal-council-on-the-arts-and-the-humanities")
  /// Federal Crop Insurance Corporation (`federal-crop-insurance-corporation`).
  public static let federalCropInsuranceCorporation = Self(
    rawValue: "federal-crop-insurance-corporation")
  /// Federal Deposit Insurance Corporation (`federal-deposit-insurance-corporation`).
  public static let federalDepositInsuranceCorporation = Self(
    rawValue: "federal-deposit-insurance-corporation")
  /// Federal Election Commission (`federal-election-commission`).
  public static let federalElectionCommission = Self(rawValue: "federal-election-commission")
  /// Federal Emergency Management Agency (`federal-emergency-management-agency`).
  public static let federalEmergencyManagementAgency = Self(
    rawValue: "federal-emergency-management-agency")
  /// Federal Energy Regulatory Commission (`federal-energy-regulatory-commission`).
  public static let federalEnergyRegulatoryCommission = Self(
    rawValue: "federal-energy-regulatory-commission")
  /// Federal Financial Institutions Examination Council (`federal-financial-institutions-examination-council`).
  public static let federalFinancialInstitutionsExaminationCouncil = Self(
    rawValue: "federal-financial-institutions-examination-council")
  /// Federal Highway Administration (`federal-highway-administration`).
  public static let federalHighwayAdministration = Self(rawValue: "federal-highway-administration")
  /// Federal Housing Enterprise Oversight Office (`federal-housing-enterprise-oversight-office`).
  public static let federalHousingEnterpriseOversightOffice = Self(
    rawValue: "federal-housing-enterprise-oversight-office")
  /// Federal Housing Finance Agency (`federal-housing-finance-agency`).
  public static let federalHousingFinanceAgency = Self(rawValue: "federal-housing-finance-agency")
  /// Federal Housing Finance Board (`federal-housing-finance-board`).
  public static let federalHousingFinanceBoard = Self(rawValue: "federal-housing-finance-board")
  /// Federal Labor Relations Authority (`federal-labor-relations-authority`).
  public static let federalLaborRelationsAuthority = Self(
    rawValue: "federal-labor-relations-authority")
  /// Federal Law Enforcement Training Center (`federal-law-enforcement-training-center`).
  public static let federalLawEnforcementTrainingCenter = Self(
    rawValue: "federal-law-enforcement-training-center")
  /// Federal Maritime Commission (`federal-maritime-commission`).
  public static let federalMaritimeCommission = Self(rawValue: "federal-maritime-commission")
  /// Federal Mediation and Conciliation Service (`federal-mediation-and-conciliation-service`).
  public static let federalMediationAndConciliationService = Self(
    rawValue: "federal-mediation-and-conciliation-service")
  /// Federal Mine Safety and Health Review Commission (`federal-mine-safety-and-health-review-commission`).
  public static let federalMineSafetyAndHealthReviewCommission = Self(
    rawValue: "federal-mine-safety-and-health-review-commission")
  /// Federal Motor Carrier Safety Administration (`federal-motor-carrier-safety-administration`).
  public static let federalMotorCarrierSafetyAdministration = Self(
    rawValue: "federal-motor-carrier-safety-administration")
  /// Federal Pay, Advisory Committee (`federal-pay-advisory-committee`).
  public static let federalPayAdvisoryCommittee = Self(rawValue: "federal-pay-advisory-committee")
  /// Federal Permitting Improvement Steering Council (`federal-permitting-improvement-steering-council`).
  public static let federalPermittingImprovementSteeringCouncil = Self(
    rawValue: "federal-permitting-improvement-steering-council")
  /// Federal Prison Industries (`federal-prison-industries`).
  public static let federalPrisonIndustries = Self(rawValue: "federal-prison-industries")
  /// Federal Procurement Policy Office (`federal-procurement-policy-office`).
  public static let federalProcurementPolicyOffice = Self(
    rawValue: "federal-procurement-policy-office")
  /// Federal Railroad Administration (`federal-railroad-administration`).
  public static let federalRailroadAdministration = Self(
    rawValue: "federal-railroad-administration")
  /// Federal Register, Administrative Committee (`federal-register-administrative-committee`).
  public static let federalRegisterAdministrativeCommittee = Self(
    rawValue: "federal-register-administrative-committee")
  /// Federal Register Office (`federal-register-office`).
  public static let federalRegisterOffice = Self(rawValue: "federal-register-office")
  /// Federal Reserve System (`federal-reserve-system`).
  public static let federalReserveSystem = Self(rawValue: "federal-reserve-system")
  /// Federal Retirement Thrift Investment Board (`federal-retirement-thrift-investment-board`).
  public static let federalRetirementThriftInvestmentBoard = Self(
    rawValue: "federal-retirement-thrift-investment-board")
  /// Federal Service Impasses Panel (`federal-service-impasses-panel`).
  public static let federalServiceImpassesPanel = Self(rawValue: "federal-service-impasses-panel")
  /// Federal Trade Commission (`federal-trade-commission`).
  public static let federalTradeCommission = Self(rawValue: "federal-trade-commission")
  /// Federal Transit Administration (`federal-transit-administration`).
  public static let federalTransitAdministration = Self(rawValue: "federal-transit-administration")
  /// Financial Crimes Enforcement Network (`financial-crimes-enforcement-network`).
  public static let financialCrimesEnforcementNetwork = Self(
    rawValue: "financial-crimes-enforcement-network")
  /// Financial Crisis Inquiry Commission (`financial-crisis-inquiry-commission`).
  public static let financialCrisisInquiryCommission = Self(
    rawValue: "financial-crisis-inquiry-commission")
  /// Financial Research Office (`financial-research-office`).
  public static let financialResearchOffice = Self(rawValue: "financial-research-office")
  /// Financial Stability Oversight Council (`financial-stability-oversight-council`).
  public static let financialStabilityOversightCouncil = Self(
    rawValue: "financial-stability-oversight-council")
  /// First Responder Network Authority (`first-responder-network-authority`).
  public static let firstResponderNetworkAuthority = Self(
    rawValue: "first-responder-network-authority")
  /// Fiscal Service (`fiscal-service`).
  public static let fiscalService = Self(rawValue: "fiscal-service")
  /// Fish and Wildlife Service (`fish-and-wildlife-service`).
  public static let fishAndWildlifeService = Self(rawValue: "fish-and-wildlife-service")
  /// Food and Consumer Service (`food-and-consumer-service`).
  public static let foodAndConsumerService = Self(rawValue: "food-and-consumer-service")
  /// Food and Drug Administration (`food-and-drug-administration`).
  public static let foodAndDrugAdministration = Self(rawValue: "food-and-drug-administration")
  /// Food and Nutrition Administration (`food-and-nutrition-administration`).
  public static let foodAndNutritionAdministration = Self(
    rawValue: "food-and-nutrition-administration")
  /// Food and Nutrition Service (`food-and-nutrition-service`).
  public static let foodAndNutritionService = Self(rawValue: "food-and-nutrition-service")
  /// Food Safety and Inspection Service (`food-safety-and-inspection-service`).
  public static let foodSafetyAndInspectionService = Self(
    rawValue: "food-safety-and-inspection-service")
  /// Foreign Agricultural Service (`foreign-agricultural-service`).
  public static let foreignAgriculturalService = Self(rawValue: "foreign-agricultural-service")
  /// Foreign Assets Control Office (`foreign-assets-control-office`).
  public static let foreignAssetsControlOffice = Self(rawValue: "foreign-assets-control-office")
  /// Foreign Claims Settlement Commission (`foreign-claims-settlement-commission`).
  public static let foreignClaimsSettlementCommission = Self(
    rawValue: "foreign-claims-settlement-commission")
  /// Foreign Service Grievance Board (`foreign-service-grievance-board`).
  public static let foreignServiceGrievanceBoard = Self(rawValue: "foreign-service-grievance-board")
  /// Foreign Service Impasse Disputes Panel (`foreign-service-impasse-disputes-panel`).
  public static let foreignServiceImpasseDisputesPanel = Self(
    rawValue: "foreign-service-impasse-disputes-panel")
  /// Foreign Service Labor Relations Board (`foreign-service-labor-relations-board`).
  public static let foreignServiceLaborRelationsBoard = Self(
    rawValue: "foreign-service-labor-relations-board")
  /// Foreign-Trade Zones Board (`foreign-trade-zones-board`).
  public static let foreignTradeZonesBoard = Self(rawValue: "foreign-trade-zones-board")
  /// Forest Service (`forest-service`).
  public static let forestService = Self(rawValue: "forest-service")
  /// General Services Administration (`general-services-administration`).
  public static let generalServicesAdministration = Self(
    rawValue: "general-services-administration")
  /// Geographic Names Board (`geographic-names-board`).
  public static let geographicNamesBoard = Self(rawValue: "geographic-names-board")
  /// Geological Survey (`geological-survey`).
  public static let geologicalSurvey = Self(rawValue: "geological-survey")
  /// Government Accountability Office (`government-accountability-office`).
  public static let governmentAccountabilityOffice = Self(
    rawValue: "government-accountability-office")
  /// Government Ethics Office (`government-ethics-office`).
  public static let governmentEthicsOffice = Self(rawValue: "government-ethics-office")
  /// Government National Mortgage Association (`government-national-mortgage-association`).
  public static let governmentNationalMortgageAssociation = Self(
    rawValue: "government-national-mortgage-association")
  /// Government Publishing Office (`government-publishing-office`).
  public static let governmentPublishingOffice = Self(rawValue: "government-publishing-office")
  /// Grain Inspection, Packers and Stockyards Administration (`grain-inspection-packers-and-stockyards-administration`).
  public static let grainInspectionPackersAndStockyardsAdministration = Self(
    rawValue: "grain-inspection-packers-and-stockyards-administration")
  /// Great Lakes St. Lawrence Seaway Development Corporation (`great-lakes-st-lawrence-seaway-development-corporation`).
  public static let greatLakesStLawrenceSeawayDevelopmentCorporation = Self(
    rawValue: "great-lakes-st-lawrence-seaway-development-corporation")
  /// Gulf Coast Ecosystem Restoration Council (`gulf-coast-ecosystem-restoration-council`).
  public static let gulfCoastEcosystemRestorationCouncil = Self(
    rawValue: "gulf-coast-ecosystem-restoration-council")
  /// Harry S. Truman Scholarship Foundation (`harry-s-truman-scholarship-foundation`).
  public static let harrySTrumanScholarshipFoundation = Self(
    rawValue: "harry-s-truman-scholarship-foundation")
  /// Health and Human Services Department (`health-and-human-services-department`).
  public static let healthAndHumanServicesDepartment = Self(
    rawValue: "health-and-human-services-department")
  /// Health Care Finance Administration (`health-care-finance-administration`).
  public static let healthCareFinanceAdministration = Self(
    rawValue: "health-care-finance-administration")
  /// Health Resources and Services Administration (`health-resources-and-services-administration`).
  public static let healthResourcesAndServicesAdministration = Self(
    rawValue: "health-resources-and-services-administration")
  /// Hearings and Appeals Office, Energy Department (`hearings-and-appeals-office-energy-department`).
  public static let hearingsAndAppealsOfficeEnergyDepartment = Self(
    rawValue: "hearings-and-appeals-office-energy-department")
  /// Hearings and Appeals Office, Interior Department (`hearings-and-appeals-office-interior-department`).
  public static let hearingsAndAppealsOfficeInteriorDepartment = Self(
    rawValue: "hearings-and-appeals-office-interior-department")
  /// Homeland Security Department (`homeland-security-department`).
  public static let homelandSecurityDepartment = Self(rawValue: "homeland-security-department")
  /// Housing and Urban Development Department (`housing-and-urban-development-department`).
  public static let housingAndUrbanDevelopmentDepartment = Self(
    rawValue: "housing-and-urban-development-department")
  /// Immigration and Naturalization Service (`immigration-and-naturalization-service`).
  public static let immigrationAndNaturalizationService = Self(
    rawValue: "immigration-and-naturalization-service")
  /// Indian Affairs Bureau (`indian-affairs-bureau`).
  public static let indianAffairsBureau = Self(rawValue: "indian-affairs-bureau")
  /// Indian Arts and Crafts Board (`indian-arts-and-crafts-board`).
  public static let indianArtsAndCraftsBoard = Self(rawValue: "indian-arts-and-crafts-board")
  /// Indian Health Service (`indian-health-service`).
  public static let indianHealthService = Self(rawValue: "indian-health-service")
  /// Indian Trust Transition Office (`indian-trust-transition-office`).
  public static let indianTrustTransitionOffice = Self(rawValue: "indian-trust-transition-office")
  /// Industry and Security Bureau (`industry-and-security-bureau`).
  public static let industryAndSecurityBureau = Self(rawValue: "industry-and-security-bureau")
  /// Information Security Oversight Office (`information-security-oversight-office`).
  public static let informationSecurityOversightOffice = Self(
    rawValue: "information-security-oversight-office")
  /// Inspector General Office, Agriculture Department (`inspector-general-office-agriculture-department`).
  public static let inspectorGeneralOfficeAgricultureDepartment = Self(
    rawValue: "inspector-general-office-agriculture-department")
  /// Inspector General Office, Health and Human Services Department (`inspector-general-office-health-and-human-services-department`).
  public static let inspectorGeneralOfficeHealthAndHumanServicesDepartment = Self(
    rawValue: "inspector-general-office-health-and-human-services-department")
  /// Inspector General Office, Interior Department (`inspector-general-office-interior-department`).
  public static let inspectorGeneralOfficeInteriorDepartment = Self(
    rawValue: "inspector-general-office-interior-department")
  /// Inspector General Office, Treasury Department (`inspector-general-office-treasury-department`).
  public static let inspectorGeneralOfficeTreasuryDepartment = Self(
    rawValue: "inspector-general-office-treasury-department")
  /// Institute of American Indian and Alaska Native Culture and Arts Development (`institute-of-american-indian-and-alaska-native-culture-and-arts-development`).
  public static let instituteOfAmericanIndianAndAlaskaNativeCultureAndArtsDevelopment = Self(
    rawValue: "institute-of-american-indian-and-alaska-native-culture-and-arts-development")
  /// Institute of Museum and Library Services (`institute-of-museum-and-library-services`).
  public static let instituteOfMuseumAndLibraryServices = Self(
    rawValue: "institute-of-museum-and-library-services")
  /// Intellectual Property Enforcement Coordinator Office (`intellectual-property-enforcement-coordinator-office`).
  public static let intellectualPropertyEnforcementCoordinatorOffice = Self(
    rawValue: "intellectual-property-enforcement-coordinator-office")
  /// Inter-American Foundation (`inter-american-foundation`).
  public static let interAmericanFoundation = Self(rawValue: "inter-american-foundation")
  /// Interagency Floodplain Management Review Committee (`interagency-floodplain-management-review-committee`).
  public static let interagencyFloodplainManagementReviewCommittee = Self(
    rawValue: "interagency-floodplain-management-review-committee")
  /// Intergovernmental Relations Advisory Commission (`intergovernmental-relations-advisory-commission`).
  public static let intergovernmentalRelationsAdvisoryCommission = Self(
    rawValue: "intergovernmental-relations-advisory-commission")
  /// Interior Department (`interior-department`).
  public static let interiorDepartment = Self(rawValue: "interior-department")
  /// Internal Revenue Service (`internal-revenue-service`).
  public static let internalRevenueService = Self(rawValue: "internal-revenue-service")
  /// International Boundary and Water Commission, United States and Mexico (`international-boundary-and-water-commission-united-states-and-mexico`).
  public static let internationalBoundaryAndWaterCommissionUnitedStatesAndMexico = Self(
    rawValue: "international-boundary-and-water-commission-united-states-and-mexico")
  /// International Broadcasting Advisory Board (`international-broadcasting-advisory-board`).
  public static let internationalBroadcastingAdvisoryBoard = Self(
    rawValue: "international-broadcasting-advisory-board")
  /// International Broadcasting Board (`international-broadcasting-board`).
  public static let internationalBroadcastingBoard = Self(
    rawValue: "international-broadcasting-board")
  /// International Development Cooperation Agency (`international-development-cooperation-agency`).
  public static let internationalDevelopmentCooperationAgency = Self(
    rawValue: "international-development-cooperation-agency")
  /// International Investment Office (`international-investment-office`).
  public static let internationalInvestmentOffice = Self(
    rawValue: "international-investment-office")
  /// International Joint Commission-United States and Canada (`international-joint-commission-united-states-and-canada`).
  public static let internationalJointCommissionUnitedStatesAndCanada = Self(
    rawValue: "international-joint-commission-united-states-and-canada")
  /// International Organizations Employees Loyalty Board (`international-organizations-employees-loyalty-board`).
  public static let internationalOrganizationsEmployeesLoyaltyBoard = Self(
    rawValue: "international-organizations-employees-loyalty-board")
  /// International Trade Administration (`international-trade-administration`).
  public static let internationalTradeAdministration = Self(
    rawValue: "international-trade-administration")
  /// International Trade Commission (`international-trade-commission`).
  public static let internationalTradeCommission = Self(rawValue: "international-trade-commission")
  /// Interstate Commerce Commission (`interstate-commerce-commission`).
  public static let interstateCommerceCommission = Self(rawValue: "interstate-commerce-commission")
  /// Investment Security Office (`investment-security-office`).
  public static let investmentSecurityOffice = Self(rawValue: "investment-security-office")
  /// James Madison Memorial Fellowship Foundation (`james-madison-memorial-fellowship-foundation`).
  public static let jamesMadisonMemorialFellowshipFoundation = Self(
    rawValue: "james-madison-memorial-fellowship-foundation")
  /// Japan-United States Friendship Commission (`japan-united-states-friendship-commission`).
  public static let japanUnitedStatesFriendshipCommission = Self(
    rawValue: "japan-united-states-friendship-commission")
  /// Joint Board for Enrollment of Actuaries (`joint-board-for-enrollment-of-actuaries`).
  public static let jointBoardForEnrollmentOfActuaries = Self(
    rawValue: "joint-board-for-enrollment-of-actuaries")
  /// Judicial Conference of the United States (`judicial-conference-of-the-united-states`).
  public static let judicialConferenceOfTheUnitedStates = Self(
    rawValue: "judicial-conference-of-the-united-states")
  /// Judicial Review Commission on Foreign Asset Control (`judicial-review-commission-on-foreign-asset-control`).
  public static let judicialReviewCommissionOnForeignAssetControl = Self(
    rawValue: "judicial-review-commission-on-foreign-asset-control")
  /// Justice Department (`justice-department`).
  public static let justiceDepartment = Self(rawValue: "justice-department")
  /// Justice Programs Office (`justice-programs-office`).
  public static let justiceProgramsOffice = Self(rawValue: "justice-programs-office")
  /// Juvenile Justice and Delinquency Prevention Office (`juvenile-justice-and-delinquency-prevention-office`).
  public static let juvenileJusticeAndDelinquencyPreventionOffice = Self(
    rawValue: "juvenile-justice-and-delinquency-prevention-office")
  /// Labor Department (`labor-department`).
  public static let laborDepartment = Self(rawValue: "labor-department")
  /// Labor-Management Standards Office (`labor-management-standards-office`).
  public static let laborManagementStandardsOffice = Self(
    rawValue: "labor-management-standards-office")
  /// Labor Statistics Bureau (`labor-statistics-bureau`).
  public static let laborStatisticsBureau = Self(rawValue: "labor-statistics-bureau")
  /// Land Management Bureau (`land-management-bureau`).
  public static let landManagementBureau = Self(rawValue: "land-management-bureau")
  /// Legal Services Corporation (`legal-services-corporation`).
  public static let legalServicesCorporation = Self(rawValue: "legal-services-corporation")
  /// Library of Congress (`library-of-congress`).
  public static let libraryOfCongress = Self(rawValue: "library-of-congress")
  /// Local Television Loan Guarantee Board (`local-television-loan-guarantee-board`).
  public static let localTelevisionLoanGuaranteeBoard = Self(
    rawValue: "local-television-loan-guarantee-board")
  /// Management and Budget Office (`management-and-budget-office`).
  public static let managementAndBudgetOffice = Self(rawValue: "management-and-budget-office")
  /// Marine Mammal Commission (`marine-mammal-commission`).
  public static let marineMammalCommission = Self(rawValue: "marine-mammal-commission")
  /// Marine Minerals Administration (`marine-minerals-administration`).
  public static let marineMineralsAdministration = Self(rawValue: "marine-minerals-administration")
  /// Maritime Administration (`maritime-administration`).
  public static let maritimeAdministration = Self(rawValue: "maritime-administration")
  /// Medicare Payment Advisory Commission (`medicare-payment-advisory-commission`).
  public static let medicarePaymentAdvisoryCommission = Self(
    rawValue: "medicare-payment-advisory-commission")
  /// Merit Systems Protection Board (`merit-systems-protection-board`).
  public static let meritSystemsProtectionBoard = Self(rawValue: "merit-systems-protection-board")
  /// Military Compensation and Retirement Modernization Commission (`military-compensation-and-retirement-modernization-commission`).
  public static let militaryCompensationAndRetirementModernizationCommission = Self(
    rawValue: "military-compensation-and-retirement-modernization-commission")
  /// Millennium Challenge Corporation (`millennium-challenge-corporation`).
  public static let millenniumChallengeCorporation = Self(
    rawValue: "millennium-challenge-corporation")
  /// Mine Safety and Health Administration (`mine-safety-and-health-administration`).
  public static let mineSafetyAndHealthAdministration = Self(
    rawValue: "mine-safety-and-health-administration")
  /// Minerals Management Service (`minerals-management-service`).
  public static let mineralsManagementService = Self(rawValue: "minerals-management-service")
  /// Mines Bureau (`mines-bureau`).
  public static let minesBureau = Self(rawValue: "mines-bureau")
  /// Minority Business Development Agency (`minority-business-development-agency`).
  public static let minorityBusinessDevelopmentAgency = Self(
    rawValue: "minority-business-development-agency")
  /// Minority Economic Impact Office (`minority-economic-impact-office`).
  public static let minorityEconomicImpactOffice = Self(rawValue: "minority-economic-impact-office")
  /// Mississippi River Commission (`mississippi-river-commission`).
  public static let mississippiRiverCommission = Self(rawValue: "mississippi-river-commission")
  /// Monetary Offices (`monetary-offices`).
  public static let monetaryOffices = Self(rawValue: "monetary-offices")
  /// Morris K. Udall and Stewart L. Udall Foundation (`morris-k-udall-and-stewart-l-udall-foundation`).
  public static let morrisKUdallAndStewartLUdallFoundation = Self(
    rawValue: "morris-k-udall-and-stewart-l-udall-foundation")
  /// National Aeronautics and Space Administration (`national-aeronautics-and-space-administration`).
  public static let nationalAeronauticsAndSpaceAdministration = Self(
    rawValue: "national-aeronautics-and-space-administration")
  /// National Agricultural Library (`national-agricultural-library`).
  public static let nationalAgriculturalLibrary = Self(rawValue: "national-agricultural-library")
  /// National Agricultural Statistics Service (`national-agricultural-statistics-service`).
  public static let nationalAgriculturalStatisticsService = Self(
    rawValue: "national-agricultural-statistics-service")
  /// National Archives and Records Administration (`national-archives-and-records-administration`).
  public static let nationalArchivesAndRecordsAdministration = Self(
    rawValue: "national-archives-and-records-administration")
  /// National Assessment Governing Board (`national-assessment-governing-board`).
  public static let nationalAssessmentGoverningBoard = Self(
    rawValue: "national-assessment-governing-board")
  /// National Bankruptcy Review Commission (`national-bankruptcy-review-commission`).
  public static let nationalBankruptcyReviewCommission = Self(
    rawValue: "national-bankruptcy-review-commission")
  /// National Biological Service (`national-biological-service`).
  public static let nationalBiologicalService = Self(rawValue: "national-biological-service")
  /// National Bipartisan Commission on Future of Medicare (`national-bipartisan-commission-on-future-of-medicare`).
  public static let nationalBipartisanCommissionOnFutureOfMedicare = Self(
    rawValue: "national-bipartisan-commission-on-future-of-medicare")
  /// National Capital Planning Commission (`national-capital-planning-commission`).
  public static let nationalCapitalPlanningCommission = Self(
    rawValue: "national-capital-planning-commission")
  /// National Civilian Community Corps (`national-civilian-community-corps`).
  public static let nationalCivilianCommunityCorps = Self(
    rawValue: "national-civilian-community-corps")
  /// National Commission on Fiscal Responsibility and Reform (`national-commission-on-fiscal-responsibility-and-reform`).
  public static let nationalCommissionOnFiscalResponsibilityAndReform = Self(
    rawValue: "national-commission-on-fiscal-responsibility-and-reform")
  /// National Commission on Intermodal Transportation (`national-commission-on-intermodal-transportation`).
  public static let nationalCommissionOnIntermodalTransportation = Self(
    rawValue: "national-commission-on-intermodal-transportation")
  /// National Commission on Libraries and Information Science (`national-commission-on-libraries-and-information-science`).
  public static let nationalCommissionOnLibrariesAndInformationScience = Self(
    rawValue: "national-commission-on-libraries-and-information-science")
  /// National Commission on Manufactured Housing (`national-commission-on-manufactured-housing`).
  public static let nationalCommissionOnManufacturedHousing = Self(
    rawValue: "national-commission-on-manufactured-housing")
  /// National Commission on Military, National, and Public Service (`national-commission-on-military-national-and-public-service`).
  public static let nationalCommissionOnMilitaryNationalAndPublicService = Self(
    rawValue: "national-commission-on-military-national-and-public-service")
  /// National Commission on Terrorist Attacks Upon the United States (`national-commission-on-terrorist-attacks-upon-the-united-states`).
  public static let nationalCommissionOnTerroristAttacksUponTheUnitedStates = Self(
    rawValue: "national-commission-on-terrorist-attacks-upon-the-united-states")
  /// National Commission on the Cost of Higher Education (`national-commission-on-the-cost-of-higher-education`).
  public static let nationalCommissionOnTheCostOfHigherEducation = Self(
    rawValue: "national-commission-on-the-cost-of-higher-education")
  /// National Commission on the Future of the Navy (`national-commission-on-the-future-of-the-navy`).
  public static let nationalCommissionOnTheFutureOfTheNavy = Self(
    rawValue: "national-commission-on-the-future-of-the-navy")
  /// National Communications System (`national-communications-system`).
  public static let nationalCommunicationsSystem = Self(rawValue: "national-communications-system")
  /// National Consumer Cooperative Bank (`national-consumer-cooperative-bank`).
  public static let nationalConsumerCooperativeBank = Self(
    rawValue: "national-consumer-cooperative-bank")
  /// National Council on Disability (`national-council-on-disability`).
  public static let nationalCouncilOnDisability = Self(rawValue: "national-council-on-disability")
  /// National Counterintelligence Center (`national-counterintelligence-center`).
  public static let nationalCounterintelligenceCenter = Self(
    rawValue: "national-counterintelligence-center")
  /// National Credit Union Administration (`national-credit-union-administration`).
  public static let nationalCreditUnionAdministration = Self(
    rawValue: "national-credit-union-administration")
  /// National Crime Prevention and Privacy Compact Council (`national-crime-prevention-and-privacy-compact-council`).
  public static let nationalCrimePreventionAndPrivacyCompactCouncil = Self(
    rawValue: "national-crime-prevention-and-privacy-compact-council")
  /// National Economic Council (`national-economic-council`).
  public static let nationalEconomicCouncil = Self(rawValue: "national-economic-council")
  /// National Education Goals Panel (`national-education-goals-panel`).
  public static let nationalEducationGoalsPanel = Self(rawValue: "national-education-goals-panel")
  /// National Endowment for the Arts (`national-endowment-for-the-arts`).
  public static let nationalEndowmentForTheArts = Self(rawValue: "national-endowment-for-the-arts")
  /// National Endowment for the Humanities (`national-endowment-for-the-humanities`).
  public static let nationalEndowmentForTheHumanities = Self(
    rawValue: "national-endowment-for-the-humanities")
  /// National Foundation on the Arts and the Humanities (`national-foundation-on-the-arts-and-the-humanities`).
  public static let nationalFoundationOnTheArtsAndTheHumanities = Self(
    rawValue: "national-foundation-on-the-arts-and-the-humanities")
  /// National Gambling Impact Study Commission (`national-gambling-impact-study-commission`).
  public static let nationalGamblingImpactStudyCommission = Self(
    rawValue: "national-gambling-impact-study-commission")
  /// National Geospatial-Intelligence Agency (`national-geospatial-intelligence-agency`).
  public static let nationalGeospatialIntelligenceAgency = Self(
    rawValue: "national-geospatial-intelligence-agency")
  /// National Highway Traffic Safety Administration (`national-highway-traffic-safety-administration`).
  public static let nationalHighwayTrafficSafetyAdministration = Self(
    rawValue: "national-highway-traffic-safety-administration")
  /// National Historical Publications and Records Commission (`national-historical-publications-and-records-commission`).
  public static let nationalHistoricalPublicationsAndRecordsCommission = Self(
    rawValue: "national-historical-publications-and-records-commission")
  /// National Indian Gaming Commission (`national-indian-gaming-commission`).
  public static let nationalIndianGamingCommission = Self(
    rawValue: "national-indian-gaming-commission")
  /// National Institute for Literacy (`national-institute-for-literacy`).
  public static let nationalInstituteForLiteracy = Self(rawValue: "national-institute-for-literacy")
  /// National Institute of Corrections (`national-institute-of-corrections`).
  public static let nationalInstituteOfCorrections = Self(
    rawValue: "national-institute-of-corrections")
  /// National Institute of Food and Agriculture (`national-institute-of-food-and-agriculture`).
  public static let nationalInstituteOfFoodAndAgriculture = Self(
    rawValue: "national-institute-of-food-and-agriculture")
  /// National Institute of Justice (`national-institute-of-justice`).
  public static let nationalInstituteOfJustice = Self(rawValue: "national-institute-of-justice")
  /// National Institute of Standards and Technology (`national-institute-of-standards-and-technology`).
  public static let nationalInstituteOfStandardsAndTechnology = Self(
    rawValue: "national-institute-of-standards-and-technology")
  /// National Institutes of Health (`national-institutes-of-health`).
  public static let nationalInstitutesOfHealth = Self(rawValue: "national-institutes-of-health")
  /// National Intelligence, Office of the National Director (`national-intelligence-office-of-the-national-director`).
  public static let nationalIntelligenceOfficeOfTheNationalDirector = Self(
    rawValue: "national-intelligence-office-of-the-national-director")
  /// National Labor Relations Board (`national-labor-relations-board`).
  public static let nationalLaborRelationsBoard = Self(rawValue: "national-labor-relations-board")
  /// National Library of Medicine (`national-library-of-medicine`).
  public static let nationalLibraryOfMedicine = Self(rawValue: "national-library-of-medicine")
  /// National Mediation Board (`national-mediation-board`).
  public static let nationalMediationBoard = Self(rawValue: "national-mediation-board")
  /// National Nanotechnology Coordination Office (`national-nanotechnology-coordination-office`).
  public static let nationalNanotechnologyCoordinationOffice = Self(
    rawValue: "national-nanotechnology-coordination-office")
  /// National Nuclear Security Administration (`national-nuclear-security-administration`).
  public static let nationalNuclearSecurityAdministration = Self(
    rawValue: "national-nuclear-security-administration")
  /// National Oceanic and Atmospheric Administration (`national-oceanic-and-atmospheric-administration`).
  public static let nationalOceanicAndAtmosphericAdministration = Self(
    rawValue: "national-oceanic-and-atmospheric-administration")
  /// National Park Service (`national-park-service`).
  public static let nationalParkService = Self(rawValue: "national-park-service")
  /// National Partnership for Reinventing Government (`national-partnership-for-reinventing-government`).
  public static let nationalPartnershipForReinventingGovernment = Self(
    rawValue: "national-partnership-for-reinventing-government")
  /// National Prison Rape Elimination Commission (`national-prison-rape-elimination-commission`).
  public static let nationalPrisonRapeEliminationCommission = Self(
    rawValue: "national-prison-rape-elimination-commission")
  /// National Railroad Passenger Corporation (`national-railroad-passenger-corporation`).
  public static let nationalRailroadPassengerCorporation = Self(
    rawValue: "national-railroad-passenger-corporation")
  /// National Science Foundation (`national-science-foundation`).
  public static let nationalScienceFoundation = Self(rawValue: "national-science-foundation")
  /// National Security Agency/Central Security Service (`national-security-agency-central-security-service`).
  public static let nationalSecurityAgencyCentralSecurityService = Self(
    rawValue: "national-security-agency-central-security-service")
  /// National Security Commission on Artificial Intelligence (`national-security-commission-on-artificial-intelligence`).
  public static let nationalSecurityCommissionOnArtificialIntelligence = Self(
    rawValue: "national-security-commission-on-artificial-intelligence")
  /// National Security Council (`national-security-council`).
  public static let nationalSecurityCouncil = Self(rawValue: "national-security-council")
  /// National Shipping Authority (`national-shipping-authority`).
  public static let nationalShippingAuthority = Self(rawValue: "national-shipping-authority")
  /// National Skill Standards Board (`national-skill-standards-board`).
  public static let nationalSkillStandardsBoard = Self(rawValue: "national-skill-standards-board")
  /// National Space Council (`national-space-council`).
  public static let nationalSpaceCouncil = Self(rawValue: "national-space-council")
  /// National Technical Information Service (`national-technical-information-service`).
  public static let nationalTechnicalInformationService = Self(
    rawValue: "national-technical-information-service")
  /// National Telecommunications and Information Administration (`national-telecommunications-and-information-administration`).
  public static let nationalTelecommunicationsAndInformationAdministration = Self(
    rawValue: "national-telecommunications-and-information-administration")
  /// National Transportation Safety Board (`national-transportation-safety-board`).
  public static let nationalTransportationSafetyBoard = Self(
    rawValue: "national-transportation-safety-board")
  /// National Women's Business Council (`national-women-s-business-council`).
  public static let nationalWomenSBusinessCouncil = Self(
    rawValue: "national-women-s-business-council")
  /// Natural Resources Conservation Service (`natural-resources-conservation-service`).
  public static let naturalResourcesConservationService = Self(
    rawValue: "natural-resources-conservation-service")
  /// Natural Resources Revenue Office (`natural-resources-revenue-office`).
  public static let naturalResourcesRevenueOffice = Self(
    rawValue: "natural-resources-revenue-office")
  /// Navajo and Hopi Indian Relocation Office (`navajo-and-hopi-indian-relocation-office`).
  public static let navajoAndHopiIndianRelocationOffice = Self(
    rawValue: "navajo-and-hopi-indian-relocation-office")
  /// Navy Department (`navy-department`).
  public static let navyDepartment = Self(rawValue: "navy-department")
  /// Neighborhood Reinvestment Corporation (`neighborhood-reinvestment-corporation`).
  public static let neighborhoodReinvestmentCorporation = Self(
    rawValue: "neighborhood-reinvestment-corporation")
  /// Northeast Dairy Compact Commission (`northeast-dairy-compact-commission`).
  public static let northeastDairyCompactCommission = Self(
    rawValue: "northeast-dairy-compact-commission")
  /// Northeast Interstate Low-Level Radioactive Waste Commission (`northeast-interstate-low-level-radioactive-waste-commission`).
  public static let northeastInterstateLowLevelRadioactiveWasteCommission = Self(
    rawValue: "northeast-interstate-low-level-radioactive-waste-commission")
  /// Northern Border Regional Commission (`northern-border-regional-commission`).
  public static let northernBorderRegionalCommission = Self(
    rawValue: "northern-border-regional-commission")
  /// Nuclear Energy Office (`nuclear-energy-office`).
  public static let nuclearEnergyOffice = Self(rawValue: "nuclear-energy-office")
  /// Nuclear Regulatory Commission (`nuclear-regulatory-commission`).
  public static let nuclearRegulatoryCommission = Self(rawValue: "nuclear-regulatory-commission")
  /// Nuclear Waste Technical Review Board (`nuclear-waste-technical-review-board`).
  public static let nuclearWasteTechnicalReviewBoard = Self(
    rawValue: "nuclear-waste-technical-review-board")
  /// Occupational Safety and Health Administration (`occupational-safety-and-health-administration`).
  public static let occupationalSafetyAndHealthAdministration = Self(
    rawValue: "occupational-safety-and-health-administration")
  /// Occupational Safety and Health Review Commission (`occupational-safety-and-health-review-commission`).
  public static let occupationalSafetyAndHealthReviewCommission = Self(
    rawValue: "occupational-safety-and-health-review-commission")
  /// Ocean Energy Management Bureau (`ocean-energy-management-bureau`).
  public static let oceanEnergyManagementBureau = Self(rawValue: "ocean-energy-management-bureau")
  /// Ocean Energy Management, Regulation, and Enforcement Bureau (`ocean-energy-management-regulation-and-enforcement-bureau`).
  public static let oceanEnergyManagementRegulationAndEnforcementBureau = Self(
    rawValue: "ocean-energy-management-regulation-and-enforcement-bureau")
  /// Ocean Policy Commission (`ocean-policy-commission`).
  public static let oceanPolicyCommission = Self(rawValue: "ocean-policy-commission")
  /// Office of Government Information Services (`office-of-government-information-services`).
  public static let officeOfGovernmentInformationServices = Self(
    rawValue: "office-of-government-information-services")
  /// Office of Motor Carrier Safety (`office-of-motor-carrier-safety`).
  public static let officeOfMotorCarrierSafety = Self(rawValue: "office-of-motor-carrier-safety")
  /// Office of National Drug Control Policy (`office-of-national-drug-control-policy`).
  public static let officeOfNationalDrugControlPolicy = Self(
    rawValue: "office-of-national-drug-control-policy")
  /// Office of Policy Development (`office-of-policy-development`).
  public static let officeOfPolicyDevelopment = Self(rawValue: "office-of-policy-development")
  /// Office of the Chief Financial Officer, Agriculture Department (`office-of-the-chief-financial-officer-agriculture-department`).
  public static let officeOfTheChiefFinancialOfficerAgricultureDepartment = Self(
    rawValue: "office-of-the-chief-financial-officer-agriculture-department")
  /// Office of the National Cyber Director (`office-of-the-national-cyber-director`).
  public static let officeOfTheNationalCyberDirector = Self(
    rawValue: "office-of-the-national-cyber-director")
  /// Oklahoma City National Memorial Trust (`oklahoma-city-national-memorial-trust`).
  public static let oklahomaCityNationalMemorialTrust = Self(
    rawValue: "oklahoma-city-national-memorial-trust")
  /// Operations Office (`operations-office`).
  public static let operationsOffice = Self(rawValue: "operations-office")
  /// Ounce of Prevention Council (`ounce-of-prevention-council`).
  public static let ounceOfPreventionCouncil = Self(rawValue: "ounce-of-prevention-council")
  /// Overseas Private Investment Corporation (`overseas-private-investment-corporation`).
  public static let overseasPrivateInvestmentCorporation = Self(
    rawValue: "overseas-private-investment-corporation")
  /// Pacific Northwest Electric Power and Conservation Planning Council (`pacific-northwest-electric-power-and-conservation-planning-council`).
  public static let pacificNorthwestElectricPowerAndConservationPlanningCouncil = Self(
    rawValue: "pacific-northwest-electric-power-and-conservation-planning-council")
  /// Panama Canal Commission (`panama-canal-commission`).
  public static let panamaCanalCommission = Self(rawValue: "panama-canal-commission")
  /// Parole Commission (`parole-commission`).
  public static let paroleCommission = Self(rawValue: "parole-commission")
  /// Partnerships and Public Engagement Office (`partnerships-and-public-engagement-office`).
  public static let partnershipsAndPublicEngagementOffice = Self(
    rawValue: "partnerships-and-public-engagement-office")
  /// Patent and Trademark Office (`patent-and-trademark-office`).
  public static let patentAndTrademarkOffice = Self(rawValue: "patent-and-trademark-office")
  /// Peace Corps (`peace-corps`).
  public static let peaceCorps = Self(rawValue: "peace-corps")
  /// Pension and Welfare Benefits Administration (`pension-and-welfare-benefits-administration`).
  public static let pensionAndWelfareBenefitsAdministration = Self(
    rawValue: "pension-and-welfare-benefits-administration")
  /// Pension Benefit Guaranty Corporation (`pension-benefit-guaranty-corporation`).
  public static let pensionBenefitGuarantyCorporation = Self(
    rawValue: "pension-benefit-guaranty-corporation")
  /// Personnel Management Office (`personnel-management-office`).
  public static let personnelManagementOffice = Self(rawValue: "personnel-management-office")
  /// Physician Payment Review Commission (`physician-payment-review-commission`).
  public static let physicianPaymentReviewCommission = Self(
    rawValue: "physician-payment-review-commission")
  /// Pipeline and Hazardous Materials Safety Administration (`pipeline-and-hazardous-materials-safety-administration`).
  public static let pipelineAndHazardousMaterialsSafetyAdministration = Self(
    rawValue: "pipeline-and-hazardous-materials-safety-administration")
  /// Postal Rate Commission (`postal-rate-commission`).
  public static let postalRateCommission = Self(rawValue: "postal-rate-commission")
  /// Postal Regulatory Commission (`postal-regulatory-commission`).
  public static let postalRegulatoryCommission = Self(rawValue: "postal-regulatory-commission")
  /// Postal Service (`postal-service`).
  public static let postalService = Self(rawValue: "postal-service")
  /// President's Council on Integrity and Efficiency (`president-s-council-on-integrity-and-efficiency`).
  public static let presidentSCouncilOnIntegrityAndEfficiency = Self(
    rawValue: "president-s-council-on-integrity-and-efficiency")
  /// President's Council on Sustainable Development (`president-s-council-on-sustainable-development`).
  public static let presidentSCouncilOnSustainableDevelopment = Self(
    rawValue: "president-s-council-on-sustainable-development")
  /// President's Critical Infrastructure Protection Board (`president-s-critical-infrastructure-protection-board`).
  public static let presidentSCriticalInfrastructureProtectionBoard = Self(
    rawValue: "president-s-critical-infrastructure-protection-board")
  /// President's Economic Policy Advisory Board (`president-s-economic-policy-advisory-board`).
  public static let presidentSEconomicPolicyAdvisoryBoard = Self(
    rawValue: "president-s-economic-policy-advisory-board")
  /// Presidential Advisory Committee on Gulf War Veterans' Illnesses (`presidential-advisory-committee-on-gulf-war-veterans-illnesses`).
  public static let presidentialAdvisoryCommitteeOnGulfWarVeteransIllnesses = Self(
    rawValue: "presidential-advisory-committee-on-gulf-war-veterans-illnesses")
  /// Presidential Commission on Assignment of Women in the Armed Forces (`presidential-commission-on-assignment-of-women-in-the-armed-forces`).
  public static let presidentialCommissionOnAssignmentOfWomenInTheArmedForces = Self(
    rawValue: "presidential-commission-on-assignment-of-women-in-the-armed-forces")
  /// Presidio Trust (`presidio-trust`).
  public static let presidioTrust = Self(rawValue: "presidio-trust")
  /// Prisons Bureau (`prisons-bureau`).
  public static let prisonsBureau = Self(rawValue: "prisons-bureau")
  /// Privacy and Civil Liberties Oversight Board (`privacy-and-civil-liberties-oversight-board`).
  public static let privacyAndCivilLibertiesOversightBoard = Self(
    rawValue: "privacy-and-civil-liberties-oversight-board")
  /// Procurement and Property Management, Office of (`procurement-and-property-management-office-of`).
  public static let procurementAndPropertyManagementOfficeOf = Self(
    rawValue: "procurement-and-property-management-office-of")
  /// Program Support Center (`program-support-center`).
  public static let programSupportCenter = Self(rawValue: "program-support-center")
  /// Prospective Payment Assessment Commission (`prospective-payment-assessment-commission`).
  public static let prospectivePaymentAssessmentCommission = Self(
    rawValue: "prospective-payment-assessment-commission")
  /// Public Buildings Reform Board (`public-buildings-reform-board`).
  public static let publicBuildingsReformBoard = Self(rawValue: "public-buildings-reform-board")
  /// Public Debt Bureau (`public-debt-bureau`).
  public static let publicDebtBureau = Self(rawValue: "public-debt-bureau")
  /// Public Health Service (`public-health-service`).
  public static let publicHealthService = Self(rawValue: "public-health-service")
  /// Railroad Retirement Board (`railroad-retirement-board`).
  public static let railroadRetirementBoard = Self(rawValue: "railroad-retirement-board")
  /// Reagan-Udall Foundation for the Food and Drug Administration (`reagan-udall-foundation-for-the-food-and-drug-administration`).
  public static let reaganUdallFoundationForTheFoodAndDrugAdministration = Self(
    rawValue: "reagan-udall-foundation-for-the-food-and-drug-administration")
  /// Reclamation Bureau (`reclamation-bureau`).
  public static let reclamationBureau = Self(rawValue: "reclamation-bureau")
  /// Recovery Accountability and Transparency Board (`recovery-accountability-and-transparency-board`).
  public static let recoveryAccountabilityAndTransparencyBoard = Self(
    rawValue: "recovery-accountability-and-transparency-board")
  /// Refugee Resettlement Office (`refugee-resettlement-office`).
  public static let refugeeResettlementOffice = Self(rawValue: "refugee-resettlement-office")
  /// Regulatory Information Service Center (`regulatory-information-service-center`).
  public static let regulatoryInformationServiceCenter = Self(
    rawValue: "regulatory-information-service-center")
  /// Research and Innovative Technology Administration (`research-and-innovative-technology-administration`).
  public static let researchAndInnovativeTechnologyAdministration = Self(
    rawValue: "research-and-innovative-technology-administration")
  /// Research and Special Programs Administration (`research-and-special-programs-administration`).
  public static let researchAndSpecialProgramsAdministration = Self(
    rawValue: "research-and-special-programs-administration")
  /// Resolution Trust Corporation (`resolution-trust-corporation`).
  public static let resolutionTrustCorporation = Self(rawValue: "resolution-trust-corporation")
  /// Risk Management Agency (`risk-management-agency`).
  public static let riskManagementAgency = Self(rawValue: "risk-management-agency")
  /// Rural Business-Cooperative Service (`rural-business-cooperative-service`).
  public static let ruralBusinessCooperativeService = Self(
    rawValue: "rural-business-cooperative-service")
  /// Rural Housing and Community Development Service (`rural-housing-and-community-development-service`).
  public static let ruralHousingAndCommunityDevelopmentService = Self(
    rawValue: "rural-housing-and-community-development-service")
  /// Rural Housing Service (`rural-housing-service`).
  public static let ruralHousingService = Self(rawValue: "rural-housing-service")
  /// Rural Telephone Bank (`rural-telephone-bank`).
  public static let ruralTelephoneBank = Self(rawValue: "rural-telephone-bank")
  /// Rural Utilities Service (`rural-utilities-service`).
  public static let ruralUtilitiesService = Self(rawValue: "rural-utilities-service")
  /// Safety and Environmental Enforcement Bureau (`safety-and-environmental-enforcement-bureau`).
  public static let safetyAndEnvironmentalEnforcementBureau = Self(
    rawValue: "safety-and-environmental-enforcement-bureau")
  /// Saint Lawrence Seaway Development Corporation (`saint-lawrence-seaway-development-corporation`).
  public static let saintLawrenceSeawayDevelopmentCorporation = Self(
    rawValue: "saint-lawrence-seaway-development-corporation")
  /// Science and Technology Policy Office (`science-and-technology-policy-office`).
  public static let scienceAndTechnologyPolicyOffice = Self(
    rawValue: "science-and-technology-policy-office")
  /// Secret Service (`secret-service`).
  public static let secretService = Self(rawValue: "secret-service")
  /// Securities and Exchange Commission (`securities-and-exchange-commission`).
  public static let securitiesAndExchangeCommission = Self(
    rawValue: "securities-and-exchange-commission")
  /// Selective Service System (`selective-service-system`).
  public static let selectiveServiceSystem = Self(rawValue: "selective-service-system")
  /// Small Business Administration (`small-business-administration`).
  public static let smallBusinessAdministration = Self(rawValue: "small-business-administration")
  /// Smithsonian Institution (`smithsonian-institution`).
  public static let smithsonianInstitution = Self(rawValue: "smithsonian-institution")
  /// Social Security Administration (`social-security-administration`).
  public static let socialSecurityAdministration = Self(rawValue: "social-security-administration")
  /// Southeastern Power Administration (`southeastern-power-administration`).
  public static let southeasternPowerAdministration = Self(
    rawValue: "southeastern-power-administration")
  /// Southwestern Power Administration (`southwestern-power-administration`).
  public static let southwesternPowerAdministration = Self(
    rawValue: "southwestern-power-administration")
  /// Special Counsel Office (`special-counsel-office`).
  public static let specialCounselOffice = Self(rawValue: "special-counsel-office")
  /// Special Inspector General for Afghanistan Reconstruction (`special-inspector-general-for-afghanistan-reconstruction`).
  public static let specialInspectorGeneralForAfghanistanReconstruction = Self(
    rawValue: "special-inspector-general-for-afghanistan-reconstruction")
  /// Special Inspector General For Iraq Reconstruction (`special-inspector-general-for-iraq-reconstruction`).
  public static let specialInspectorGeneralForIraqReconstruction = Self(
    rawValue: "special-inspector-general-for-iraq-reconstruction")
  /// Special Trustee for American Indians Office (`special-trustee-for-american-indians-office`).
  public static let specialTrusteeForAmericanIndiansOffice = Self(
    rawValue: "special-trustee-for-american-indians-office")
  /// State Department (`state-department`).
  public static let stateDepartment = Self(rawValue: "state-department")
  /// State Justice Institute (`state-justice-institute`).
  public static let stateJusticeInstitute = Self(rawValue: "state-justice-institute")
  /// Strategic Preparedness and Response Administration (`strategic-preparedness-and-response-administration`).
  public static let strategicPreparednessAndResponseAdministration = Self(
    rawValue: "strategic-preparedness-and-response-administration")
  /// Substance Abuse and Mental Health Services Administration (`substance-abuse-and-mental-health-services-administration`).
  public static let substanceAbuseAndMentalHealthServicesAdministration = Self(
    rawValue: "substance-abuse-and-mental-health-services-administration")
  /// Surface Mining Reclamation and Enforcement Office (`surface-mining-reclamation-and-enforcement-office`).
  public static let surfaceMiningReclamationAndEnforcementOffice = Self(
    rawValue: "surface-mining-reclamation-and-enforcement-office")
  /// Surface Transportation Board (`surface-transportation-board`).
  public static let surfaceTransportationBoard = Self(rawValue: "surface-transportation-board")
  /// Susquehanna River Basin Commission (`susquehanna-river-basin-commission`).
  public static let susquehannaRiverBasinCommission = Self(
    rawValue: "susquehanna-river-basin-commission")
  /// Technology Administration (`technology-administration`).
  public static let technologyAdministration = Self(rawValue: "technology-administration")
  /// Tennessee Valley Authority (`tennessee-valley-authority`).
  public static let tennesseeValleyAuthority = Self(rawValue: "tennessee-valley-authority")
  /// The White House Office (`the-white-house-office`).
  public static let theWhiteHouseOffice = Self(rawValue: "the-white-house-office")
  /// Thrift Depositor Protection Oversight Board (`thrift-depositor-protection-oversight-board`).
  public static let thriftDepositorProtectionOversightBoard = Self(
    rawValue: "thrift-depositor-protection-oversight-board")
  /// Thrift Supervision Office (`thrift-supervision-office`).
  public static let thriftSupervisionOffice = Self(rawValue: "thrift-supervision-office")
  /// Trade and Development Agency (`trade-and-development-agency`).
  public static let tradeAndDevelopmentAgency = Self(rawValue: "trade-and-development-agency")
  /// Trade Representative, Office of United States (`trade-representative-office-of-united-states`).
  public static let tradeRepresentativeOfficeOfUnitedStates = Self(
    rawValue: "trade-representative-office-of-united-states")
  /// Transportation Department (`transportation-department`).
  public static let transportationDepartment = Self(rawValue: "transportation-department")
  /// Transportation Office (`transportation-office`).
  public static let transportationOffice = Self(rawValue: "transportation-office")
  /// Transportation Security Administration (`transportation-security-administration`).
  public static let transportationSecurityAdministration = Self(
    rawValue: "transportation-security-administration")
  /// Transportation Statistics Bureau (`transportation-statistics-bureau`).
  public static let transportationStatisticsBureau = Self(
    rawValue: "transportation-statistics-bureau")
  /// Travel and Tourism Administration (`travel-and-tourism-administration`).
  public static let travelAndTourismAdministration = Self(
    rawValue: "travel-and-tourism-administration")
  /// Treasury Department (`treasury-department`).
  public static let treasuryDepartment = Self(rawValue: "treasury-department")
  /// Twenty-First Century Workforce Commission (`twenty-first-century-workforce-commission`).
  public static let twentyFirstCenturyWorkforceCommission = Self(
    rawValue: "twenty-first-century-workforce-commission")
  /// U.S.-China Economic and Security Review Commission (`u-s-china-economic-and-security-review-commission`).
  public static let uSChinaEconomicAndSecurityReviewCommission = Self(
    rawValue: "u-s-china-economic-and-security-review-commission")
  /// U.S. Citizenship and Immigration Services (`u-s-citizenship-and-immigration-services`).
  public static let uSCitizenshipAndImmigrationServices = Self(
    rawValue: "u-s-citizenship-and-immigration-services")
  /// U.S. Committee on the Marine Transportation System (`u-s-committee-on-the-marine-transportation-system`).
  public static let uSCommitteeOnTheMarineTransportationSystem = Self(
    rawValue: "u-s-committee-on-the-marine-transportation-system")
  /// U.S. Customs and Border Protection (`u-s-customs-and-border-protection`).
  public static let uSCustomsAndBorderProtection = Self(
    rawValue: "u-s-customs-and-border-protection")
  /// U.S. House of Representatives (`u-s-house-of-representatives`).
  public static let uSHouseOfRepresentatives = Self(rawValue: "u-s-house-of-representatives")
  /// U.S. Immigration and Customs Enforcement (`u-s-immigration-and-customs-enforcement`).
  public static let uSImmigrationAndCustomsEnforcement = Self(
    rawValue: "u-s-immigration-and-customs-enforcement")
  /// U.S. International Development Finance Corporation (`u-s-international-development-finance-corporation`).
  public static let uSInternationalDevelopmentFinanceCorporation = Self(
    rawValue: "u-s-international-development-finance-corporation")
  /// U.S. Trade Deficit Review Commission (`u-s-trade-deficit-review-commission`).
  public static let uSTradeDeficitReviewCommission = Self(
    rawValue: "u-s-trade-deficit-review-commission")
  /// Under-Secretary for Economic Affairs (`under-secretary-for-economic-affairs`).
  public static let underSecretaryForEconomicAffairs = Self(
    rawValue: "under-secretary-for-economic-affairs")
  /// Unified Carrier Registration Plan (`unified-carrier-registration-plan`).
  public static let unifiedCarrierRegistrationPlan = Self(
    rawValue: "unified-carrier-registration-plan")
  /// Uniformed Services University of the Health Sciences (`uniformed-services-university-of-the-health-sciences`).
  public static let uniformedServicesUniversityOfTheHealthSciences = Self(
    rawValue: "uniformed-services-university-of-the-health-sciences")
  /// United States Agency for Global Media (`united-states-agency-for-global-media`).
  public static let unitedStatesAgencyForGlobalMedia = Self(
    rawValue: "united-states-agency-for-global-media")
  /// United States Enrichment Corporation (`united-states-enrichment-corporation`).
  public static let unitedStatesEnrichmentCorporation = Self(
    rawValue: "united-states-enrichment-corporation")
  /// United States Information Agency (`united-states-information-agency`).
  public static let unitedStatesInformationAgency = Self(
    rawValue: "united-states-information-agency")
  /// United States Institute of Peace (`united-states-institute-of-peace`).
  public static let unitedStatesInstituteOfPeace = Self(
    rawValue: "united-states-institute-of-peace")
  /// United States Marshals Service (`united-states-marshals-service`).
  public static let unitedStatesMarshalsService = Self(rawValue: "united-states-marshals-service")
  /// United States Mint (`united-states-mint`).
  public static let unitedStatesMint = Self(rawValue: "united-states-mint")
  /// United States Olympic and Paralympic Committee (`united-states-olympic-and-paralympic-committee`).
  public static let unitedStatesOlympicAndParalympicCommittee = Self(
    rawValue: "united-states-olympic-and-paralympic-committee")
  /// United States Sentencing Commission (`united-states-sentencing-commission`).
  public static let unitedStatesSentencingCommission = Self(
    rawValue: "united-states-sentencing-commission")
  /// U.S. Codex Office (`us-codex-office`).
  public static let usCodexOffice = Self(rawValue: "us-codex-office")
  /// Utah Reclamation Mitigation and Conservation Commission (`utah-reclamation-mitigation-and-conservation-commission`).
  public static let utahReclamationMitigationAndConservationCommission = Self(
    rawValue: "utah-reclamation-mitigation-and-conservation-commission")
  /// Valles Caldera Trust (`valles-caldera-trust`).
  public static let vallesCalderaTrust = Self(rawValue: "valles-caldera-trust")
  /// Veterans Affairs Department (`veterans-affairs-department`).
  public static let veteransAffairsDepartment = Self(rawValue: "veterans-affairs-department")
  /// Veterans Employment and Training Service (`veterans-employment-and-training-service`).
  public static let veteransEmploymentAndTrainingService = Self(
    rawValue: "veterans-employment-and-training-service")
  /// Victims of Crime Office (`victims-of-crime-office`).
  public static let victimsOfCrimeOffice = Self(rawValue: "victims-of-crime-office")
  /// Wage and Hour Division (`wage-and-hour-division`).
  public static let wageAndHourDivision = Self(rawValue: "wage-and-hour-division")
  /// Western Area Power Administration (`western-area-power-administration`).
  public static let westernAreaPowerAdministration = Self(
    rawValue: "western-area-power-administration")
  /// Women's Business Enterprise Interagency Committee (`women-s-business-enterprise-interagency-committee`).
  public static let womenSBusinessEnterpriseInteragencyCommittee = Self(
    rawValue: "women-s-business-enterprise-interagency-committee")
  /// Women's Progress Commemoration Commission (`women-s-progress-commemoration-commission`).
  public static let womenSProgressCommemorationCommission = Self(
    rawValue: "women-s-progress-commemoration-commission")
  /// Women's Suffrage Centennial Commission (`women-s-suffrage-centennial-commission`).
  public static let womenSSuffrageCentennialCommission = Self(
    rawValue: "women-s-suffrage-centennial-commission")
  /// Workers' Compensation Programs Office (`workers-compensation-programs-office`).
  public static let workersCompensationProgramsOffice = Self(
    rawValue: "workers-compensation-programs-office")
}
