#!/usr/bin/env python3
"""Generate the AgencyIdentifier catalog from a recorded /api/v1/agencies.json snapshot.

The catalog is one `public static let` per unique slug, named in lowerCamelCase from the slug and
sorted by identifier in byte order. Output passes through `swift format` with the repository's
configuration so the committed file is canonical and `--check` compares like with like.
"""

import argparse
import hashlib
import json
import pathlib
import re
import subprocess
import sys
import tempfile

SOURCE_URL = "https://www.federalregister.gov/api/v1/agencies.json"
SLUG_PATTERN = re.compile(r"[a-z0-9]+(-[a-z0-9]+)*")
IDENTIFIER_PATTERN = re.compile(r"[A-Za-z_][A-Za-z0-9_]*")

# Words Swift reserves in every position; a member named after one is written in backticks.
SWIFT_KEYWORDS = frozenset(
    """
    Any Self any as associatedtype await break case catch class continue default defer deinit do
    else enum extension fallthrough false fileprivate for func guard if import in init inout
    internal is let nil open operator precedencegroup private protocol public repeat rethrows
    return self static struct subscript super switch throw throws true try typealias var where
    while
    """.split()
)


class CatalogError(ValueError):
    """A snapshot or mapping that cannot become a catalog; the message is the report."""


def identifier_for(slug):
    """Derive a lowerCamelCase Swift identifier from a hyphenated slug."""
    parts = slug.split("-")
    return parts[0] + "".join(part[:1].upper() + part[1:] for part in parts[1:])


def escaped(identifier):
    return f"`{identifier}`" if identifier in SWIFT_KEYWORDS else identifier


def catalog_entries(agencies, names):
    """Return (identifier, slug, display name) triples sorted by identifier bytes, or raise."""
    problems = []
    seen_slugs = set()
    entries = []
    for index, agency in enumerate(agencies):
        if not isinstance(agency, dict):
            problems.append(f"entry {index}: not an object")
            continue
        slug = agency.get("slug")
        name = agency.get("name")
        if not isinstance(slug, str) or not slug:
            problems.append(f"entry {index}: missing or empty slug")
            continue
        if slug in seen_slugs:
            problems.append(f"entry {index}: duplicate slug {slug!r}")
            continue
        seen_slugs.add(slug)
        if not isinstance(name, str) or not name:
            problems.append(f"entry {index}: slug {slug!r} has no display name")
            continue
        identifier = names.get(slug)
        if identifier is None:
            if not SLUG_PATTERN.fullmatch(slug):
                problems.append(
                    f"entry {index}: slug {slug!r} needs a reviewed identifier in --names"
                )
                continue
            identifier = identifier_for(slug)
        if not IDENTIFIER_PATTERN.fullmatch(identifier):
            problems.append(
                f"entry {index}: slug {slug!r} maps to {identifier!r}, not a Swift identifier"
            )
            continue
        entries.append((identifier, slug, name))
    for slug in sorted(set(names) - seen_slugs):
        problems.append(f"--names maps {slug!r}, which the snapshot does not contain")
    by_identifier = {}
    for identifier, slug, _ in entries:
        by_identifier.setdefault(identifier, []).append(slug)
    for identifier, slugs in sorted(by_identifier.items()):
        if len(slugs) > 1:
            problems.append(f"identifier {identifier!r} collides for slugs {slugs!r}")
    if problems:
        raise CatalogError("\n".join(problems))
    return sorted(entries, key=lambda entry: entry[0].encode("utf-8"))


def render(entries, digest):
    lines = [
        "// Generated by Scripts/generate-agency-identifiers.py. Edit the generator, not this file.",
        f"// Source: {SOURCE_URL}",
        f"// Snapshot SHA-256: {digest}",
        "",
        "extension AgencyIdentifier {",
    ]
    for identifier, slug, name in entries:
        lines.append(f"  /// {name} (`{slug}`).")
        lines.append(f'  public static let {escaped(identifier)} = Self(rawValue: "{slug}")')
    lines.append("}")
    return "\n".join(lines) + "\n"


def formatted(source, configuration):
    """Run the repository's swift-format over the rendered source; the toolchain is required."""
    with tempfile.NamedTemporaryFile("w", suffix=".swift", delete=False) as handle:
        handle.write(source)
        path = pathlib.Path(handle.name)
    try:
        result = subprocess.run(
            ["swift", "format", "--configuration", str(configuration), str(path)],
            capture_output=True,
            text=True,
            encoding="utf-8",
            check=False,
        )
    except FileNotFoundError as error:
        raise CatalogError("swift toolchain not found; swift format is required") from error
    finally:
        path.unlink()
    if result.returncode != 0:
        raise CatalogError(f"swift format failed:\n{result.stderr}")
    return result.stdout


def generate(input_path, names_path, configuration):
    """Return (catalog source, entry count) for one snapshot, or raise CatalogError."""
    data = input_path.read_bytes()
    agencies = json.loads(data)
    if not isinstance(agencies, list) or not agencies:
        raise CatalogError("snapshot must be a nonempty JSON array of agencies")
    names = {}
    if names_path is not None:
        names = json.loads(names_path.read_text(encoding="utf-8"))
        if not isinstance(names, dict) or not all(
            isinstance(key, str) and isinstance(value, str) for key, value in names.items()
        ):
            raise CatalogError("--names must be a JSON object of slug to identifier strings")
    entries = catalog_entries(agencies, names)
    digest = hashlib.sha256(data).hexdigest()
    return formatted(render(entries, digest), configuration), len(entries)


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", required=True, type=pathlib.Path, help="Recorded agencies.json")
    parser.add_argument("--output", required=True, type=pathlib.Path, help="Swift catalog file")
    parser.add_argument("--names", type=pathlib.Path, help="Reviewed slug-to-identifier JSON")
    parser.add_argument(
        "--check", action="store_true", help="Regenerate and compare; nonzero on any drift"
    )
    parser.add_argument(
        "--configuration",
        type=pathlib.Path,
        default=pathlib.Path(__file__).resolve().parent.parent / ".swift-format",
        help="swift-format configuration (default: the repository's .swift-format)",
    )
    arguments = parser.parse_args(argv)
    try:
        source, count = generate(arguments.input, arguments.names, arguments.configuration)
    except (CatalogError, OSError, ValueError) as error:
        print(f"generate-agency-identifiers: {error}", file=sys.stderr)
        return 1
    if arguments.check:
        current = (
            arguments.output.read_text(encoding="utf-8") if arguments.output.exists() else None
        )
        if current != source:
            print(
                f"generate-agency-identifiers: {arguments.output} drifts from {arguments.input}",
                file=sys.stderr,
            )
            return 1
        print(f"{count} agency identifiers match {arguments.output}")
        return 0
    arguments.output.write_text(source, encoding="utf-8")
    print(f"{count} agency identifiers written to {arguments.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
